# Generated by Django 5.2.1 on 2025-05-10 11:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(help_text='Material icon name', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('project_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, help_text='Краткое описание вашей специализации', max_length=100)),
                ('bio', models.TextField(blank=True, help_text='Расскажите о себе и своем опыте')),
                ('skills', models.CharField(blank=True, help_text='Перечислите ваши навыки через запятую', max_length=255)),
                ('experience', models.CharField(choices=[('beginner', 'Начинающий (менее 1 года)'), ('intermediate', 'Средний (1-3 года)'), ('advanced', 'Опытный (3-5 лет)'), ('expert', 'Эксперт (более 5 лет)')], default='beginner', max_length=20)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, help_text='Ваша часовая ставка в рублях', max_digits=8)),
                ('availability', models.CharField(choices=[('full_time', 'Полная занятость'), ('part_time', 'Частичная занятость'), ('project_based', 'Проектная работа'), ('not_available', 'Временно не доступен')], default='full_time', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('telegram', models.CharField(blank=True, max_length=50)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('portfolio_url', models.URLField(blank=True, help_text='Ссылка на ваше портфолио')),
                ('education', models.TextField(blank=True, help_text='Информация о вашем образовании')),
                ('certifications', models.TextField(blank=True, help_text='Информация о ваших сертификатах')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('completed_projects', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False, help_text='Подтвержденный фрилансер')),
                ('is_featured', models.BooleanField(default=False, help_text='Отображать в списке рекомендуемых')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='freelancers', to='freelancers.category')),
            ],
            options={
                'ordering': ['-rating', '-completed_projects'],
            },
        ),
    ]
