# Generated by Django 5.2.1 on 2025-05-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='phone_number',
            field=models.CharField(blank=True, null=True),
        ),
    ]
